# Generated by Django 3.1.7 on 2021-04-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distributions',
            field=models.ManyToManyField(blank=True, to='users.Distribution'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='experience', to='users.Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='users.Framework'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hw_tools',
            field=models.ManyToManyField(blank=True, related_name='hw_tools', to='users.Tool'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests', to='users.Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languajes',
            field=models.ManyToManyField(blank=True, to='users.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sw_tools',
            field=models.ManyToManyField(blank=True, related_name='sw_tools', to='users.Tool'),
        ),
    ]
