# Generated by Django 3.1.7 on 2021-06-12 01:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210609_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='new_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='unread_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 20, 1, 55, 877982)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('team_performance', 'Desempeño de equipo'), ('personality', 'Personalidad')], max_length=17),
        ),
    ]
