# Generated by Django 3.1.7 on 2021-04-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210415_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_register',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, unique=True),
        ),
    ]
