# Generated by Django 3.1.7 on 2021-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210415_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frameworks',
            field=models.ManyToManyField(to='users.Framework'),
        ),
    ]
