# Generated by Django 3.1.7 on 2021-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210416_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='users.Framework'),
        ),
    ]
