# Generated by Django 3.1.7 on 2021-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210416_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_register',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
