# Generated by Django 3.1.7 on 2021-05-16 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20210515_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('personality', 'Personalidad'), ('team_performance', 'Desempeño de equipo')], max_length=17),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('notification_text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('join_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.joininvitation')),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.joinrequest')),
                ('task_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.taskactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
