# Generated by Django 3.1.7 on 2021-05-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210525_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='users.team'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('team_performance', 'Desempeño de equipo'), ('personality', 'Personalidad')], max_length=17),
        ),
        migrations.AlterField(
            model_name='team',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
