# Generated by Django 3.1.7 on 2021-05-26 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20210525_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('personality', 'Personalidad'), ('team_performance', 'Desempeño de equipo')], max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name='joininvitation',
            unique_together={('to_user', 'from_user', 'team')},
        ),
    ]
