# Generated by Django 3.1.7 on 2021-05-26 00:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20210525_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joininvitation',
            unique_together={('to_user', 'team')},
        ),
        migrations.RemoveField(
            model_name='joininvitation',
            name='from_user',
        ),
    ]
