# Generated by Django 3.1.7 on 2021-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210525_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Maestro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('team_performance', 'Desempeño de equipo'), ('personality', 'Personalidad')], max_length=17),
        ),
    ]
