# Generated by Django 3.1.7 on 2021-05-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210526_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.career'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_semester',
            field=models.CharField(choices=[('agosto', 'Agosto - Diciembre'), ('enero', 'Enero - Junio')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997)], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.academy'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='entry_semester',
            field=models.CharField(choices=[('agosto', 'Agosto - Diciembre'), ('enero', 'Enero - Junio')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='entry_year',
            field=models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997)], null=True),
        ),
    ]
