# Generated by Django 3.1.7 on 2021-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210528_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resource_url',
            field=models.ManyToManyField(blank=True, related_name='resource_url', to='users.ResourceURL'),
        ),
    ]
