# Generated by Django 3.1.7 on 2021-05-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_project_resource_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resource_url',
        ),
        migrations.AddField(
            model_name='resourceurl',
            name='project',
            field=models.ManyToManyField(blank=True, to='users.Project'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('personality', 'Personalidad'), ('team_performance', 'Desempeño de equipo')], max_length=17),
        ),
    ]
