# Generated by Django 3.1.7 on 2021-05-30 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_chat_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 22, 21, 26, 897626)),
        ),
    ]
