# Generated by Django 3.1.7 on 2021-05-31 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210529_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sw_tools',
            new_name='tools',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hw_tools',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 19, 52, 54, 747805)),
        ),
    ]
